apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    scrape_configs:
    - job_name: 'Spring Boot Application input'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 3s
      static_configs:
        - targets: ['data-svcs:8080']
          labels:
            application: 'data-svcs springboot app'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      containers:
      - name: prometheus
        image: prom/prometheus:v2.39.0
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        args: ["--config.file=/etc/prometheus/prometheus.yaml"]

